### ISSUE TITLE
Remove suffix of zh-CN link

### ISSUE THREAD

**Issue by jhen0409** [chentsulin/relay#10]
https://chentsulin.github.io/relay/docs/thinking-in-graphql.zh-CN.html#content

「Thinking in GraphQL」頁面連結後輟是 zh-CN，連結是顯示 [CN 翻譯的標題](https://github.com/chentsulin/relay/blob/doc-zh-tw/docs/QuickStart-ThinkingInGraphQL.zh-CN.md)，頁面顯示正常
也許應該移除那些文件？

**Comment by chentsulin** [comment]
Auto fixed by merging upstream.
