### ISSUE TITLE
翻譯進度

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/relay#2]
- [x] Read Me
- [x] Quick Start
  - [x] Getting Started
  - [x] Thinking In GraphQL
  - [x] Thinking In Relay
  - [x] Tutorial
  - [x] Videos
- [x] Guides
  - [x] Babel Plugin
  - [x] Containers
  - [x] Mutations
  - [x] Network Layer
  - [x] Ready State
  - [x] Root Container
  - [x] Routes
- [x] GraphQL
  - [x] Connections
  - [x] Further Reading
  - [x] Mutations
  - [x] Object Identification
  - [x] Relay Specification
- [x] Interfaces
  - [x] MutationRequest
  - [x] NetworkLayer
  - [x] QueryRequest
- [x] API Reference
  - [x] Container (@neighborhood999)
  - [x] Mutation
  - [x] PropTypes
  - [x] QL
  - [x] Relay
  - [x] Renderer (@neighborhood999)
  - [x] RootContainer (@neighborhood999)
  - [x] Route
  - [x] Store

**Comment by chentsulin** [comment]
@jigsawye @neighborhood999 我覺得翻的比例差不多可以貼連結宣傳了，不過這次我覺得很多中文都很不順，兩位可以幫忙閱讀一下順便修中文語句嗎？

**Comment by neighborhood999** [comment]
@chentsulin 好的！

**Comment by jigsawye** [comment]
OK，不過這兩週會比較忙QQ

**Comment by chentsulin** [comment]
👍
